#!/usr/bin/env pwsh
#Requires -Version 7.0
<#
    install.ps1 - interactive installer for the PowerShell todo.txt CLI.

    Remote one-liners:
        # interactive
        iwr https://raw.githubusercontent.com/citizen-123/todo.txt-powershell/main/install.ps1 | iex

        # non-interactive (defaults) — set the env var first because a piped
        # script cannot receive parameters directly:
        $env:TODO_INSTALL_DEFAULT='1'; iwr <url> | iex

        # non-interactive via a script block (lets you pass -Default and friends):
        & ([scriptblock]::Create((iwr <url>).Content)) -Default

    Local:
        ./install.ps1                 # interactive
        ./install.ps1 -Default        # accept all defaults

    The script fetches the project, creates the todo directory, generates a
    config file with the chosen options, and (optionally) registers a `todo`
    function in your PowerShell profile.
#>
[CmdletBinding()]
param(
    [switch]$Default,
    [string]$InstallDir,
    [string]$TodoDir,
    [string]$RepoUrl = 'https://github.com/citizen-123/todo.txt-powershell',
    [switch]$Force
)

# --- pure, testable helpers -------------------------------------------------

function New-TodoCliConfigContent {
    <#
        Builds the text of a todo config file (todo.sh `export VAR=value` syntax,
        parsed by the module's ConvertFrom-TodoConfig).
    #>
    [OutputType([string])]
    param(
        [Parameter(Mandatory)][string]$TodoDir,
        [bool]$Git = $false,
        [string]$GitRemote = '',
        [bool]$InProgress = $false,
        [bool]$DateTags = $false
    )
    $lines = [System.Collections.Generic.List[string]]::new()
    $lines.Add('# Generated by the todo.txt-powershell installer.')
    $lines.Add("export TODO_DIR=`"$TodoDir`"")
    $lines.Add("export TODOTXT_GIT=$([int][bool]$Git)")
    if ($GitRemote) { $lines.Add("export TODOTXT_GIT_REMOTE=`"$GitRemote`"") }
    $lines.Add("export TODOTXT_IN_PROGRESS=$([int][bool]$InProgress)")
    $lines.Add("export TODOTXT_DATE_TAGS=$([int][bool]$DateTags)")
    return ($lines -join "`n") + "`n"
}

function Add-TodoProfileFunction {
    <#
        Idempotently writes a `todo` function into the given PowerShell profile,
        delimited by marker comments. Running it again replaces the existing block
        rather than appending a second one. A function (not an alias) is used so
        options such as -a / -d pass through cleanly.
    #>
    param(
        [Parameter(Mandatory)][string]$ProfilePath,
        [Parameter(Mandatory)][string]$WrapperPath,
        [string]$ModulePath,
        [switch]$Completion
    )
    $start = '# >>> todo-cli >>>'
    $end = '# <<< todo-cli <<<'

    $kept = [System.Collections.Generic.List[string]]::new()
    if (Test-Path -LiteralPath $ProfilePath) {
        $inBlock = $false
        foreach ($line in (Get-Content -LiteralPath $ProfilePath)) {
            if ($line.Trim() -eq $start) { $inBlock = $true; continue }
            if ($line.Trim() -eq $end) { $inBlock = $false; continue }
            if (-not $inBlock) { $kept.Add($line) }
        }
    }
    else {
        $parent = Split-Path -Parent $ProfilePath
        if ($parent -and -not (Test-Path -LiteralPath $parent)) {
            New-Item -ItemType Directory -Force -Path $parent | Out-Null
        }
    }
    # Trim trailing blank lines so repeated runs don't accumulate whitespace.
    while ($kept.Count -gt 0 -and $kept[$kept.Count - 1].Trim() -eq '') { $kept.RemoveAt($kept.Count - 1) }

    if ($kept.Count -gt 0) { $kept.Add('') }
    $kept.Add($start)
    # A ValueFromRemainingArguments parameter (rather than $args) lets the tab
    # completer hook the command's argument values.
    $kept.Add("function todo { param([Parameter(ValueFromRemainingArguments)][string[]]`$TodoArgs) & `"$WrapperPath`" @TodoArgs }")
    if ($Completion -and $ModulePath) {
        # Import the module and register the tab-completer for the todo command.
        $kept.Add("Import-Module `"$ModulePath`"")
        $kept.Add('Register-TodoArgumentCompleter -CommandName todo')
    }
    $kept.Add($end)

    Set-Content -LiteralPath $ProfilePath -Value $kept -Encoding utf8
}

function Read-YesNo {
    [OutputType([bool])]
    param([Parameter(Mandatory)][string]$Prompt, [bool]$DefaultYes = $true)
    $suffix = if ($DefaultYes) { '[Y/n]' } else { '[y/N]' }
    $answer = Read-Host -Prompt "$Prompt $suffix"
    if ([string]::IsNullOrWhiteSpace($answer)) { return $DefaultYes }
    return ($answer -match '^(y|yes)$')
}

function Install-TodoProject {
    <# Fetches the project into $InstallDir (git clone, else zipball download). #>
    param(
        [Parameter(Mandatory)][string]$InstallDir,
        [Parameter(Mandatory)][string]$RepoUrl,
        [switch]$Force
    )
    if ((Test-Path -LiteralPath (Join-Path $InstallDir 'todo.ps1')) -and -not $Force) {
        Write-Host "Project already present at $InstallDir (use -Force to refresh)."
        return
    }
    if (Get-Command git -ErrorAction SilentlyContinue) {
        if (Test-Path -LiteralPath (Join-Path $InstallDir '.git')) {
            Write-Host "Updating existing clone in $InstallDir..."
            & git -C $InstallDir pull --quiet
        }
        else {
            Write-Host "Cloning $RepoUrl into $InstallDir..."
            & git clone --quiet $RepoUrl $InstallDir
        }
    }
    else {
        Write-Host 'git not found; downloading zip archive...'
        $zip = Join-Path ([System.IO.Path]::GetTempPath()) ("todo_" + [guid]::NewGuid().ToString('N') + '.zip')
        $tmp = Join-Path ([System.IO.Path]::GetTempPath()) ("todo_" + [guid]::NewGuid().ToString('N'))
        try {
            Invoke-WebRequest -Uri "$RepoUrl/archive/refs/heads/main.zip" -OutFile $zip
            Expand-Archive -Path $zip -DestinationPath $tmp -Force
            $inner = Get-ChildItem -LiteralPath $tmp -Directory | Select-Object -First 1
            if (-not $inner) { throw 'Downloaded archive was empty.' }
            New-Item -ItemType Directory -Force -Path $InstallDir | Out-Null
            Copy-Item -Path (Join-Path $inner.FullName '*') -Destination $InstallDir -Recurse -Force
        }
        finally {
            Remove-Item $zip, $tmp -Recurse -Force -ErrorAction SilentlyContinue
        }
    }
    if (-not (Test-Path -LiteralPath (Join-Path $InstallDir 'todo.ps1'))) {
        throw "Installation failed: $InstallDir/todo.ps1 not found after fetch."
    }
}

function Initialize-TodoGitRepo {
    <# Primes a git repo in the todo dir (idempotent), adding the remote if given. #>
    param([Parameter(Mandatory)][string]$TodoDir, [string]$Remote = '')
    if (-not (Get-Command git -ErrorAction SilentlyContinue)) {
        Write-Warning 'git was requested but is not installed; skipping repo setup.'
        return
    }
    if (-not (Test-Path -LiteralPath (Join-Path $TodoDir '.git'))) {
        & git -C $TodoDir init --quiet
    }
    if ($Remote) {
        $existing = (& git -C $TodoDir remote 2>$null)
        if ($existing -notcontains 'origin') {
            & git -C $TodoDir remote add origin $Remote
        }
    }
}

# --- orchestration ----------------------------------------------------------

function Invoke-TodoInstaller {
    param(
        [switch]$Default,
        [string]$InstallDir,
        [string]$TodoDir,
        [string]$RepoUrl,
        [switch]$Force
    )

    $useDefaults = $Default -or ($env:TODO_INSTALL_DEFAULT -eq '1')
    if (-not $InstallDir) { $InstallDir = Join-Path $HOME '.todo-cli' }
    if (-not $TodoDir) { $TodoDir = Join-Path $HOME '.todo' }

    Write-Host '== todo.txt-powershell installer ==' -ForegroundColor Cyan

    Install-TodoProject -InstallDir $InstallDir -RepoUrl $RepoUrl -Force:$Force

    New-Item -ItemType Directory -Force -Path $TodoDir | Out-Null

    # Gather options.
    $git = $false; $remote = ''; $inProgress = $false; $dateTags = $false
    $registerAlias = $true; $completion = $true
    if (-not $useDefaults) {
        $git = Read-YesNo -Prompt 'Track your todo directory with git?' -DefaultYes:$false
        if ($git) {
            if (-not (Get-Command git -ErrorAction SilentlyContinue)) {
                Write-Warning 'git is not installed. Install it and re-run, or continue without git for now.'
            }
            $r = Read-Host -Prompt 'Remote URL to push to (leave blank for local-only)'
            if (-not [string]::IsNullOrWhiteSpace($r)) { $remote = $r.Trim() }
        }
        $inProgress = Read-YesNo -Prompt 'Enable in-progress tracking (start/ip + started: tag)?' -DefaultYes:$false
        $dateTags = Read-YesNo -Prompt 'Tag tasks with added:/completed: dates?' -DefaultYes:$false
        $registerAlias = Read-YesNo -Prompt 'Register a `todo` command in your PowerShell profile?' -DefaultYes:$true
        if ($registerAlias) {
            $completion = Read-YesNo -Prompt 'Enable tab completion for actions/projects/contexts?' -DefaultYes:$true
        }
    }

    # Write the config file at the first search location ($HOME/.todo/config).
    $configDir = Join-Path $HOME '.todo'
    New-Item -ItemType Directory -Force -Path $configDir | Out-Null
    $configPath = Join-Path $configDir 'config'
    $content = New-TodoCliConfigContent -TodoDir $TodoDir -Git $git -GitRemote $remote -InProgress $inProgress -DateTags $dateTags
    if ((Test-Path -LiteralPath $configPath) -and -not $useDefaults -and -not $Force) {
        if (Read-YesNo -Prompt "Config $configPath exists. Overwrite?" -DefaultYes:$false) {
            Set-Content -LiteralPath $configPath -Value $content -NoNewline -Encoding utf8
        }
    }
    else {
        Set-Content -LiteralPath $configPath -Value $content -NoNewline -Encoding utf8
    }
    Write-Host "Wrote config: $configPath"

    if ($git) { Initialize-TodoGitRepo -TodoDir $TodoDir -Remote $remote }

    if ($registerAlias) {
        $wrapper = Join-Path $InstallDir 'todo.ps1'
        $modulePath = Join-Path $InstallDir 'src' 'TodoTxt.psd1'
        Add-TodoProfileFunction -ProfilePath $PROFILE -WrapperPath $wrapper -ModulePath $modulePath -Completion:$completion
        Write-Host "Registered 'todo' function in $PROFILE$(if ($completion) { ' (with tab completion)' })"
    }

    Write-Host ''
    Write-Host 'Done!' -ForegroundColor Green
    Write-Host "  Installed to : $InstallDir"
    Write-Host "  Todo dir     : $TodoDir"
    if ($registerAlias) {
        Write-Host '  Reload your profile to use it:  . $PROFILE'
        Write-Host '  Then try:  todo add "my first task"'
    }
    else {
        Write-Host "  Try:  & '$(Join-Path $InstallDir 'todo.ps1')' add `"my first task`""
    }
}

# Run unless dot-sourced for testing (tests set TODO_INSTALL_NORUN=1).
if ($env:TODO_INSTALL_NORUN -ne '1') {
    Invoke-TodoInstaller -Default:$Default -InstallDir $InstallDir -TodoDir $TodoDir -RepoUrl $RepoUrl -Force:$Force
}
